### PR TITLE
Handle non-integer primary key

### PR DESCRIPTION
**Pull request by hongquan**
In my project, I use `UUID` for primary key and _django-extended-history_ build a change log that cannot be saved to `LogEntry`. This PR is to fix that.

### CODE REVIEW

**Comment by RobKuipers** [comment]
Thank you for helping improve django-extended-history !

**Comment by hongquan** [comment]
Could you please release to PyPI?

**Comment by RobKuipers** [comment]
Hi, it's on PyPi since March 21. At least, that's what I think. Version 1.5.0. Did I make a mistake? 

I downloaded the .tar.gz from [PyPi](https://pypi.org/project/django-extended-history/#files). Seems to me I do see the changes?

Please advice.

**Comment by hongquan** [comment]
Thank you, my mistake.

**Pull request merged**
